### ISSUE TITLE
Tiny requests API key

### ISSUE THREAD

**Issue by vitaleg** [Worklenz/worklenz#24]
> Starting in early 2024, all editors on our cloud platform will be required to have a valid API key. Without a valid API key, your editor will transition to read-only mode, limiting your ability to make changes.
> 
> Affected users will receive a [notification in their editor](https://www.tiny.cloud/docs/tinymce/latest/cloud-troubleshooting/#A-valid-API-key-is-required-starting-2024-to-continue-using-TinyMCE.-Please-alert-your-admin-to-sign-up-to-get-your-free-API-key.). If you receive this notification, please contact the Administrator for your application/site. Admins will need to [get a valid API key](https://www.tiny.cloud/my-account/integrate/) and paste it into the code to continue using TinyMCE.

[Source](https://www.tiny.cloud/docs/tinymce/latest/invalid-api-key/?utm_campaign=invalid_origin_learn_more&utm_source=tiny&utm_medium=referral)

I tried to find the API key environment variable, but couldn't find it.

![9BH1wTn](https://github.com/Worklenz/worklenz/assets/3653714/934395e9-c14b-42c8-87db-eaa38fa85bfc)

**Comment by kalinga777** [comment]
It's better to build a new one :)

**Comment by aaron13223** [comment]
I cloned the repo and built the worklenz-frontend after editing the following files for the apiKey:

- worklenz-frontend/src/app/administrator/components/task-view/task-view-description/task-view-description.component.ts
- worklenz-frontend/src/app/administrator/settings/project-template-edit-view/components/row/task-description/task-description.component.ts

Still didn't work tho :p (I got a new key by signing up on tiny.cloud but in the browser it's still fetching from the old apiKey even after rebuilding the image)

**Comment by aaron13223** [comment]
Seems like as of now, it only works on "localhost" - I was running this on a separate machine and it wouldn't work.... Changing the apiKeys in the files I mentioned above and rebuilding the app doesn't work either since I can see the js files generated still have the old api key :/

**Comment by vitaleg** [comment]
I don't really understand why this issue is closed. 
Is your solution to always use the application on “localhost”?

**Comment by mihkuno** [comment]
> I cloned the repo and built the worklenz-frontend after editing the following files for the apiKey:
> 
> * worklenz-frontend/src/app/administrator/components/task-view/task-view-description/task-view-description.component.ts
> * worklenz-frontend/src/app/administrator/settings/project-template-edit-view/components/row/task-description/task-description.component.ts
> 
> Still didn't work tho :p (I got a new key by signing up on tiny.cloud but in the browser it's still fetching from the old apiKey even after rebuilding the image)

Got this working, just create a free api then whitelist your ip or dns in [here](https://www.tiny.cloud/my-account/integrate/#angular). The only problem with it is that its limited to 1000 editor loads per month. TinyMCE is self-hostable i think itd be nice to integrate it as a service in the compose yml

**Comment by carlosmintfan** [comment]
> > I cloned the repo and built the worklenz-frontend after editing the following files for the apiKey:
> 
> > 
> 
> > * worklenz-frontend/src/app/administrator/components/task-view/task-view-description/task-view-description.component.ts
> 
> > * worklenz-frontend/src/app/administrator/settings/project-template-edit-view/components/row/task-description/task-description.component.ts
> 
> > 
> 
> > Still didn't work tho :p (I got a new key by signing up on tiny.cloud but in the browser it's still fetching from the old apiKey even after rebuilding the image)
> 
> 
> 
> Got this working, just create a free api then whitelist your ip or dns in [here](https://www.tiny.cloud/my-account/integrate/#angular). The only problem with it is that its limited to 1000 editor loads per month. TinyMCE is self-hostable i think but it requires [attribution](https://github.com/tinymce/tinymce-docs/issues/1810) and its buggy af. Another option would be [downgrading](https://github.com/tinymce/tinymce/issues/9453) it to v6.8.3 

The cloud version requires attribution, the free self-hosted one that the project is licensed GPL.
