### ISSUE TITLE
Inconsistent interactive paradigm: "Save Changes" or not?

### ISSUE THREAD

**Issue by gdevenyi** [Worklenz/worklenz#26]
When editing a project, we get a slidebar slide in, can do editing, and then there's a "Save" button.

Meanwhile, when editing a task, we get a sideba slide in, can do editing, and everything is automatically saved.

This is inconsistent and should be unified.

**Comment by gdevenyi** [comment]
Personally, I'd like to see a "Save" button at the bottom of every slide-out panel, with a popup asking "Save" or "Discard" if I click away from the panel.

**Comment by kalinga777** [comment]
@gdevenyi This is correct. One of the reason we put the save button in project slide is for confirmation
