### ISSUE TITLE
Add pre-built docker images

### ISSUE THREAD

**Issue by TheZoker** [Worklenz/worklenz#28]
Instead of building the docker container on `docker compose up` it would be nice, if you guys would offer pre-build images on every of your releases. You can host them on dockerhub or github packages (ghcr.io). The easiest would be to create a docker workflow within github actions:
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by kalinga777** [comment]
Thanks @TheZoker. This is a good idea

**Comment by gdevenyi** [comment]
https://github.com/marketplace/actions/docker-setup-buildx
