### ISSUE TITLE
Links in comments are not converted to clickable

### ISSUE THREAD

**Issue by gdevenyi** [Worklenz/worklenz#30]
A link added in a comment to a task doesn't become clickable.

May be related to #24?

**Comment by chamikaJ** [comment]
@gdevenyi To make links in comments clickable, we'll need to integrate an editor like TinyMCE with the mentions plugin. However, we haven't added the TinyMCE editor to the task comments yet. Currently, we're using the comment component from [Ant Design of Angular](https://ng.ant.design/components/comment/en).
