### ISSUE TITLE
Emails have broken embedded image

### ISSUE THREAD

**Issue by gdevenyi** [Worklenz/worklenz#31]
![image](https://github.com/Worklenz/worklenz/assets/3001850/84b17d4d-585a-48f3-a6c3-3e7f1017385a)

**Comment by shravan20** [comment]
@gdevenyi: Could you add more context? I would like to take a look into this, if this issue is open

**Comment by gdevenyi** [comment]
This is the  code for the broken image in the worklenz.com email
```
<img width=3D"50" height=3D"50" src=
=3D"https://worklenz.com/assets/icons/icon-96x96.png" style=3D"box-shadow  =
 : 0 3px 6px -4px rgb(0 0 0 / 12%), 0 6px 16px 0 rgb(0 0 0 / 8%), 0 9px 28p=
x 8px rgb(0 0 0 / 5%);border-radius: 10px;">
```

**Comment by shravan20** [comment]
```
<img width=3D"50" height=3D"50" src=
=3D"https://worklenz.com/assets/icons/icon-96x96.png" style=3D"box-shadow  =
 : 0 3px 6px -4px rgb(0 0 0 / 12%), 0 6px 16px 0 rgb(0 0 0 / 8%), 0 9px 28p=
x 8px rgb(0 0 0 / 5%);border-radius: 10px;">
```


This would be previewing the logo right?

![](https://worklenz.com/_astro/logo.3zDlW3cW_Z19Q2ML.svg)

**Comment by gdevenyi** [comment]
It looks like its probably supposed to be just the stylzed W considering its a 96x96 PNG

**Comment by chamikaJ** [comment]
@gdevenyi The URL for the image should be updated to https://app.worklenz.com/assets/icons/icon-96x96.png to include `app` as the subdomain. I'll make the change with a PR
